apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: startmeapp-hackathon-app
  name: startmeapp-hackathon-app-controller
spec:
  replicas: 2
  selector:
    name: startmeapp-hackathon-app
  template:
    metadata:
      labels:
        name: startmeapp-hackathon-app
    spec:
      containers:
        - image: registry.hub.docker.com/angulito/startmeapp-hackathon:latest
          name: startmeapp-hackathon-app
          imagePullPolicy: Always
          ports:
          - containerPort: 5000
            name: http-server