version: 2
jobs:

  build:
    docker:
      - image: circleci/python:3.6.1
        environment:
          FLASK_CONFIG: testing

    working_directory: ~/startmeapp-hackathon

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Set docker image tag
          command: |
            SHORT_COMMIT_HASH="$(git rev-parse --short=8 HEAD)"
            if [ $CIRCLE_BRANCH == 'master' ]; then
                BRANCH_TAG_PREFIX='master'
            else
                BRANCH_TAG_PREFIX='branch'
            fi
            echo "export IMAGE_NAME=startmeapp-hackathon" >> $BASH_ENV
            echo "export IMAGE_TAG=${BRANCH_TAG_PREFIX}-${SHORT_COMMIT_HASH}" >> $BASH_ENV

      - run:
          name: Build docker image
          command: |
            docker build -t angulito/$IMAGE_NAME:$IMAGE_TAG -t angulito/$IMAGE_NAME:latest .

      - run:
          name: Push docker image
          command: |
            docker login -u $DOCKER_LOGIN -p $DOCKER_PWD
            docker push angulito/$IMAGE_NAME:$IMAGE_TAG
            docker push angulito/$IMAGE_NAME:latest

  deploy:
    docker:
      - image: google/cloud-sdk
    environment:
      - PROJECT_NAME: "startmeapp-hackathon"
      - GOOGLE_PROJECT_ID: "startmeapp-hackathon"
      - GOOGLE_COMPUTE_ZONE: "europe-west1-b"
      - GOOGLE_CLUSTER_NAME: "startmeapp-hackathon-cluster"
    steps:

      - checkout

      - run:
          name: Setup Google Cloud SDK
          command: |
            echo $GCLOUD_SERVICE_KEY | sudo gcloud auth activate-service-account --key-file=-
            sudo gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            sudo gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
            gcloud --quiet container clusters get-credentials ${GOOGLE_CLUSTER_NAME}

      - run: 
          name: Deploy to Kubernetes
          command: |
            envsubst < ./kubernetes/controller/app-controller.yml > ./patched-app-controller.yml
            envsubst < ./kubernetes/service/app-service.yml > ./patched-app-service.yml
            kubectl apply -f ./patched-app-controller.yml
            kubectl apply -f ./patched-app-service.yml
            kubectl rollout status deployment/${PROJECT_NAME}

  test:
    machine: true

    steps:
      - checkout

      - run:
          name: Set docker image tag
          command: |
            SHORT_COMMIT_HASH="$(git rev-parse --short=8 HEAD)"
            if [ $CIRCLE_BRANCH == 'master' ]; then
                BRANCH_TAG_PREFIX='master'
            else
                BRANCH_TAG_PREFIX='branch'
            fi
            echo "export IMAGE_NAME=startmeapp-hackathon" >> $BASH_ENV
            echo "export IMAGE_TAG=${BRANCH_TAG_PREFIX}-${SHORT_COMMIT_HASH}" >> $BASH_ENV

      - run:
          name: Running tests
          command: docker run -v $(pwd):/usr/app angulito/$IMAGE_NAME:$IMAGE_TAG bash -c "python -m pytest"


workflows:
  version: 2

  build-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
            - build
          filters:
            branches:
              only: master